// Code generated by "stringer -type=RequestType"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AppendEntry-0]
	_ = x[RequestVote-1]
	_ = x[ClientCommand-2]
}

const _RequestType_name = "AppendEntryRequestVoteClientCommand"

var _RequestType_index = [...]uint8{0, 11, 22, 35}

func (i RequestType) String() string {
	if i < 0 || i >= RequestType(len(_RequestType_index)-1) {
		return "RequestType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RequestType_name[_RequestType_index[i]:_RequestType_index[i+1]]
}
