// Code generated by "stringer -type=VoteStatus"; DO NOT EDIT.

package voter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Leader-0]
	_ = x[Follower-1]
	_ = x[Split-2]
}

const _VoteStatus_name = "LeaderFollowerSplit"

var _VoteStatus_index = [...]uint8{0, 6, 14, 19}

func (i VoteStatus) String() string {
	if i < 0 || i >= VoteStatus(len(_VoteStatus_index)-1) {
		return "VoteStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VoteStatus_name[_VoteStatus_index[i]:_VoteStatus_index[i+1]]
}
